name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      - name: Paketleri yükle
        run: flutter pub get

      - name: APK oluştur
        run: flutter build apk --release

      - name: APK'yı kaydet
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
